SOURCES=\
src/CuboidGenerator.cpp\
src/Particle.cpp\
src/FileReader.cpp\
src/outputWriter/VTKWriter.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/handler/CellUpdater.cpp\
src/handler/PairHandlerConverter.cpp\
src/handler/PositionCalculator.cpp\
src/handler/VelocityCalculator.cpp\
src/handler/ForceCalculator_Gravity.cpp\
src/handler/ForcePrepareHandler.cpp\
src/handler/ForceCalculator_LennardJones.cpp\
src/handler/plotHandler_VTK.cpp\
src/ParticleInput_FileReader.cpp\
src/UnitTests/countParticles.cpp\
src/UnitTests/UTest_CuboidGenerator.cpp\
src/UnitTests/UTest_CellContainer.cpp\
src/UnitTests/cuboidLengthHandler.cpp\
src/UnitTests/UTest_SimpleContainer.cpp\
src/UnitTests/marker_handler.cpp\
src/UnitTests/countPairs.cpp\
src/UnitTests/UTest_ForceCalculator_LennardJones.cpp\
src/XMLInput/XMLInput.cpp\
src/XMLInput/simulation.cpp\
src/MolSim.cpp\
src/ParticleOutput_VTK.cpp\
src/ParticleContainer/SimpleContainer.cpp\
src/ParticleContainer/CellContainer.cpp\
