SOURCES=\
src/UnitTests/countPairs.cpp\
src/UnitTests/UTest_ParticleContainer.cpp\
src/UnitTests/countParticles.cpp\
src/ParticleContainer.cpp\
src/ParticleInput_FileReader.cpp\
src/MaxwellBoltzmannDistribution.cpp\
src/outputWriter/vtk-unstructured.cpp\
src/outputWriter/VTKWriter.cpp\
src/ParticleOutput_VTK.cpp\
src/Particle.cpp\
src/CuboidGenerator.cpp\
src/FileReader.cpp\
src/MolSim.cpp\
src/handler/ForceCalculator_LennardJones.cpp\
src/handler/VelocityCalculator.cpp\
src/handler/ForcePrepareHandler.cpp\
src/handler/PositionCalculator.cpp\
src/handler/ForceCalculator_Gravity.cpp\
