// Copyright (C) 2005-2010 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

#ifndef SRC_XMLINPUT_SIMULATION_H
#define SRC_XMLINPUT_SIMULATION_H

// Begin prologue.
//
//
// End prologue.

#include <xsd/cxx/config.hxx>

#if (XSD_INT_VERSION != 3030000L)
//#error XSD runtime version mismatch
#endif

#include <xsd/cxx/pre.hxx>

#ifndef XSD_USE_CHAR
#define XSD_USE_CHAR
#endif

#ifndef XSD_CXX_TREE_USE_CHAR
#define XSD_CXX_TREE_USE_CHAR
#endif

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/types.hxx>

#include <xsd/cxx/xml/error-handler.hxx>

#include <xsd/cxx/xml/dom/auto-ptr.hxx>

#include <xsd/cxx/tree/parsing.hxx>
#include <xsd/cxx/tree/parsing/byte.hxx>
#include <xsd/cxx/tree/parsing/unsigned-byte.hxx>
#include <xsd/cxx/tree/parsing/short.hxx>
#include <xsd/cxx/tree/parsing/unsigned-short.hxx>
#include <xsd/cxx/tree/parsing/int.hxx>
#include <xsd/cxx/tree/parsing/unsigned-int.hxx>
#include <xsd/cxx/tree/parsing/long.hxx>
#include <xsd/cxx/tree/parsing/unsigned-long.hxx>
#include <xsd/cxx/tree/parsing/boolean.hxx>
#include <xsd/cxx/tree/parsing/float.hxx>
#include <xsd/cxx/tree/parsing/double.hxx>
#include <xsd/cxx/tree/parsing/decimal.hxx>

namespace xml_schema
{
  // anyType and anySimpleType.
  //
  typedef ::xsd::cxx::tree::type type;
  typedef ::xsd::cxx::tree::simple_type< type > simple_type;
  typedef ::xsd::cxx::tree::type container;

  // 8-bit
  //
  typedef signed char byte;
  typedef unsigned char unsigned_byte;

  // 16-bit
  //
  typedef short short_;
  typedef unsigned short unsigned_short;

  // 32-bit
  //
  typedef int int_;
  typedef unsigned int unsigned_int;

  // 64-bit
  //
  typedef long long long_;
  typedef unsigned long long unsigned_long;

  // Supposed to be arbitrary-length integral types.
  //
  typedef long long integer;
  typedef long long non_positive_integer;
  typedef unsigned long long non_negative_integer;
  typedef unsigned long long positive_integer;
  typedef long long negative_integer;

  // Boolean.
  //
  typedef bool boolean;

  // Floating-point types.
  //
  typedef float float_;
  typedef double double_;
  typedef double decimal;

  // String types.
  //
  typedef ::xsd::cxx::tree::string< char, simple_type > string;
  typedef ::xsd::cxx::tree::normalized_string< char, string > normalized_string;
  typedef ::xsd::cxx::tree::token< char, normalized_string > token;
  typedef ::xsd::cxx::tree::name< char, token > name;
  typedef ::xsd::cxx::tree::nmtoken< char, token > nmtoken;
  typedef ::xsd::cxx::tree::nmtokens< char, simple_type, nmtoken > nmtokens;
  typedef ::xsd::cxx::tree::ncname< char, name > ncname;
  typedef ::xsd::cxx::tree::language< char, token > language;

  // ID/IDREF.
  //
  typedef ::xsd::cxx::tree::id< char, ncname > id;
  typedef ::xsd::cxx::tree::idref< char, ncname, type > idref;
  typedef ::xsd::cxx::tree::idrefs< char, simple_type, idref > idrefs;

  // URI.
  //
  typedef ::xsd::cxx::tree::uri< char, simple_type > uri;

  // Qualified name.
  //
  typedef ::xsd::cxx::tree::qname< char, simple_type, uri, ncname > qname;

  // Binary.
  //
  typedef ::xsd::cxx::tree::buffer< char > buffer;
  typedef ::xsd::cxx::tree::base64_binary< char, simple_type > base64_binary;
  typedef ::xsd::cxx::tree::hex_binary< char, simple_type > hex_binary;

  // Date/time.
  //
  typedef ::xsd::cxx::tree::time_zone time_zone;
  typedef ::xsd::cxx::tree::date< char, simple_type > date;
  typedef ::xsd::cxx::tree::date_time< char, simple_type > date_time;
  typedef ::xsd::cxx::tree::duration< char, simple_type > duration;
  typedef ::xsd::cxx::tree::gday< char, simple_type > gday;
  typedef ::xsd::cxx::tree::gmonth< char, simple_type > gmonth;
  typedef ::xsd::cxx::tree::gmonth_day< char, simple_type > gmonth_day;
  typedef ::xsd::cxx::tree::gyear< char, simple_type > gyear;
  typedef ::xsd::cxx::tree::gyear_month< char, simple_type > gyear_month;
  typedef ::xsd::cxx::tree::time< char, simple_type > time;

  // Entity.
  //
  typedef ::xsd::cxx::tree::entity< char, ncname > entity;
  typedef ::xsd::cxx::tree::entities< char, simple_type, entity > entities;

  // Flags and properties.
  //
  typedef ::xsd::cxx::tree::flags flags;
  typedef ::xsd::cxx::tree::properties< char > properties;

  // Parsing/serialization diagnostics.
  //
  typedef ::xsd::cxx::tree::severity severity;
  typedef ::xsd::cxx::tree::error< char > error;
  typedef ::xsd::cxx::tree::diagnostics< char > diagnostics;

  // Exceptions.
  //
  typedef ::xsd::cxx::tree::exception< char > exception;
  typedef ::xsd::cxx::tree::bounds< char > bounds;
  typedef ::xsd::cxx::tree::duplicate_id< char > duplicate_id;
  typedef ::xsd::cxx::tree::parsing< char > parsing;
  typedef ::xsd::cxx::tree::expected_element< char > expected_element;
  typedef ::xsd::cxx::tree::unexpected_element< char > unexpected_element;
  typedef ::xsd::cxx::tree::expected_attribute< char > expected_attribute;
  typedef ::xsd::cxx::tree::unexpected_enumerator< char > unexpected_enumerator;
  typedef ::xsd::cxx::tree::expected_text_content< char > expected_text_content;
  typedef ::xsd::cxx::tree::no_prefix_mapping< char > no_prefix_mapping;

  // Error handler callback interface.
  //
  typedef ::xsd::cxx::xml::error_handler< char > error_handler;

  // DOM interaction.
  //
  namespace dom
  {
    // Automatic pointer for DOMDocument.
    //
    using ::xsd::cxx::xml::dom::auto_ptr;

#ifndef XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
#define XSD_CXX_TREE_TREE_NODE_KEY__XML_SCHEMA
    // DOM user data key for back pointers to tree nodes.
    //
    const XMLCh* const tree_node_key = ::xsd::cxx::tree::user_data_keys::node;
#endif
  }
}

// Forward declarations.
//
class simulation_mode_type_t;
class boundary_type_t;
class direction_t;
class boundary_t;
class simulation_force_calculator_t;
class lj_cutoff_t;
class lj_smoothed_t;
class gravity_t;
class harmonic_t;
class constant_force_t;
class simulation_mode_t;
class thermostat_t;
class thermodyn_stats_t;
class fixed_t;
class veldenprof_t;
class simulation_parameters_t;
class cuboid_t;
class sphere_t;
class membrane_t;
class simulation_input_t;
class iteration_output_t;
class result_output_t;
class simulation_output_t;
class simulation_t;

#include <memory>    // std::auto_ptr
#include <limits>    // std::numeric_limits
#include <algorithm> // std::binary_search

#include <xsd/cxx/xml/char-utf8.hxx>

#include <xsd/cxx/tree/exceptions.hxx>
#include <xsd/cxx/tree/elements.hxx>
#include <xsd/cxx/tree/containers.hxx>
#include <xsd/cxx/tree/list.hxx>

#include <xsd/cxx/xml/dom/parsing-header.hxx>

class simulation_mode_type_t: public ::xml_schema::string
{
  public:
  enum value
  {
    normal,
    linked_cell,
    membrane
  };

  simulation_mode_type_t (value v);

  simulation_mode_type_t (const char* v);

  simulation_mode_type_t (const ::std::string& v);

  simulation_mode_type_t (const ::xml_schema::string& v);

  simulation_mode_type_t (const ::xercesc::DOMElement& e,
                          ::xml_schema::flags f = 0,
                          ::xml_schema::container* c = 0);

  simulation_mode_type_t (const ::xercesc::DOMAttr& a,
                          ::xml_schema::flags f = 0,
                          ::xml_schema::container* c = 0);

  simulation_mode_type_t (const ::std::string& s,
                          const ::xercesc::DOMElement* e,
                          ::xml_schema::flags f = 0,
                          ::xml_schema::container* c = 0);

  simulation_mode_type_t (const simulation_mode_type_t& x,
                          ::xml_schema::flags f = 0,
                          ::xml_schema::container* c = 0);

  virtual simulation_mode_type_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  simulation_mode_type_t&
  operator= (value v);

  virtual
  operator value () const
  {
    return _xsd_simulation_mode_type_t_convert ();
  }

  protected:
  value
  _xsd_simulation_mode_type_t_convert () const;

  public:
  static const char* const _xsd_simulation_mode_type_t_literals_[3];
  static const value _xsd_simulation_mode_type_t_indexes_[3];
};

class boundary_type_t: public ::xml_schema::string
{
  public:
  enum value
  {
    outflow,
    reflect,
    periodic
  };

  boundary_type_t (value v);

  boundary_type_t (const char* v);

  boundary_type_t (const ::std::string& v);

  boundary_type_t (const ::xml_schema::string& v);

  boundary_type_t (const ::xercesc::DOMElement& e,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

  boundary_type_t (const ::xercesc::DOMAttr& a,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

  boundary_type_t (const ::std::string& s,
                   const ::xercesc::DOMElement* e,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

  boundary_type_t (const boundary_type_t& x,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

  virtual boundary_type_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  boundary_type_t&
  operator= (value v);

  virtual
  operator value () const
  {
    return _xsd_boundary_type_t_convert ();
  }

  protected:
  value
  _xsd_boundary_type_t_convert () const;

  public:
  static const char* const _xsd_boundary_type_t_literals_[3];
  static const value _xsd_boundary_type_t_indexes_[3];
};

class direction_t: public ::xml_schema::string
{
  public:
  enum value
  {
    x,
    y,
    z
  };

  direction_t (value v);

  direction_t (const char* v);

  direction_t (const ::std::string& v);

  direction_t (const ::xml_schema::string& v);

  direction_t (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

  direction_t (const ::xercesc::DOMAttr& a,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

  direction_t (const ::std::string& s,
               const ::xercesc::DOMElement* e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

  direction_t (const direction_t& x,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

  virtual direction_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  direction_t&
  operator= (value v);

  virtual
  operator value () const
  {
    return _xsd_direction_t_convert ();
  }

  protected:
  value
  _xsd_direction_t_convert () const;

  public:
  static const char* const _xsd_direction_t_literals_[3];
  static const value _xsd_direction_t_indexes_[3];
};

class boundary_t: public ::xml_schema::type
{
  public:
  // x_0
  // 
  typedef ::boundary_type_t x_0_type;
  typedef ::xsd::cxx::tree::traits< x_0_type, char > x_0_traits;

  const x_0_type&
  x_0 () const;

  x_0_type&
  x_0 ();

  void
  x_0 (const x_0_type& x);

  void
  x_0 (::std::auto_ptr< x_0_type > p);

  // x_max
  // 
  typedef ::boundary_type_t x_max_type;
  typedef ::xsd::cxx::tree::traits< x_max_type, char > x_max_traits;

  const x_max_type&
  x_max () const;

  x_max_type&
  x_max ();

  void
  x_max (const x_max_type& x);

  void
  x_max (::std::auto_ptr< x_max_type > p);

  // y_0
  // 
  typedef ::boundary_type_t y_0_type;
  typedef ::xsd::cxx::tree::traits< y_0_type, char > y_0_traits;

  const y_0_type&
  y_0 () const;

  y_0_type&
  y_0 ();

  void
  y_0 (const y_0_type& x);

  void
  y_0 (::std::auto_ptr< y_0_type > p);

  // y_max
  // 
  typedef ::boundary_type_t y_max_type;
  typedef ::xsd::cxx::tree::traits< y_max_type, char > y_max_traits;

  const y_max_type&
  y_max () const;

  y_max_type&
  y_max ();

  void
  y_max (const y_max_type& x);

  void
  y_max (::std::auto_ptr< y_max_type > p);

  // z_0
  // 
  typedef ::boundary_type_t z_0_type;
  typedef ::xsd::cxx::tree::traits< z_0_type, char > z_0_traits;

  const z_0_type&
  z_0 () const;

  z_0_type&
  z_0 ();

  void
  z_0 (const z_0_type& x);

  void
  z_0 (::std::auto_ptr< z_0_type > p);

  // z_max
  // 
  typedef ::boundary_type_t z_max_type;
  typedef ::xsd::cxx::tree::traits< z_max_type, char > z_max_traits;

  const z_max_type&
  z_max () const;

  z_max_type&
  z_max ();

  void
  z_max (const z_max_type& x);

  void
  z_max (::std::auto_ptr< z_max_type > p);

  // Constructors.
  //
  boundary_t (const x_0_type&,
              const x_max_type&,
              const y_0_type&,
              const y_max_type&,
              const z_0_type&,
              const z_max_type&);

  boundary_t (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

  boundary_t (const boundary_t& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

  virtual boundary_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~boundary_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< x_0_type > x_0_;
  ::xsd::cxx::tree::one< x_max_type > x_max_;
  ::xsd::cxx::tree::one< y_0_type > y_0_;
  ::xsd::cxx::tree::one< y_max_type > y_max_;
  ::xsd::cxx::tree::one< z_0_type > z_0_;
  ::xsd::cxx::tree::one< z_max_type > z_max_;
};

class simulation_force_calculator_t: public ::xml_schema::type
{
  public:
  // lennard-jones
  // 
  typedef ::lj_cutoff_t lennard_jones_type;
  typedef ::xsd::cxx::tree::sequence< lennard_jones_type > lennard_jones_sequence;
  typedef lennard_jones_sequence::iterator lennard_jones_iterator;
  typedef lennard_jones_sequence::const_iterator lennard_jones_const_iterator;
  typedef ::xsd::cxx::tree::traits< lennard_jones_type, char > lennard_jones_traits;

  const lennard_jones_sequence&
  lennard_jones () const;

  lennard_jones_sequence&
  lennard_jones ();

  void
  lennard_jones (const lennard_jones_sequence& s);

  // lj-smoothed
  // 
  typedef ::lj_smoothed_t lj_smoothed_type;
  typedef ::xsd::cxx::tree::sequence< lj_smoothed_type > lj_smoothed_sequence;
  typedef lj_smoothed_sequence::iterator lj_smoothed_iterator;
  typedef lj_smoothed_sequence::const_iterator lj_smoothed_const_iterator;
  typedef ::xsd::cxx::tree::traits< lj_smoothed_type, char > lj_smoothed_traits;

  const lj_smoothed_sequence&
  lj_smoothed () const;

  lj_smoothed_sequence&
  lj_smoothed ();

  void
  lj_smoothed (const lj_smoothed_sequence& s);

  // gravity
  // 
  typedef ::gravity_t gravity_type;
  typedef ::xsd::cxx::tree::sequence< gravity_type > gravity_sequence;
  typedef gravity_sequence::iterator gravity_iterator;
  typedef gravity_sequence::const_iterator gravity_const_iterator;
  typedef ::xsd::cxx::tree::traits< gravity_type, char > gravity_traits;

  const gravity_sequence&
  gravity () const;

  gravity_sequence&
  gravity ();

  void
  gravity (const gravity_sequence& s);

  // harmonic
  // 
  typedef ::harmonic_t harmonic_type;
  typedef ::xsd::cxx::tree::sequence< harmonic_type > harmonic_sequence;
  typedef harmonic_sequence::iterator harmonic_iterator;
  typedef harmonic_sequence::const_iterator harmonic_const_iterator;
  typedef ::xsd::cxx::tree::traits< harmonic_type, char > harmonic_traits;

  const harmonic_sequence&
  harmonic () const;

  harmonic_sequence&
  harmonic ();

  void
  harmonic (const harmonic_sequence& s);

  // constant
  // 
  typedef ::constant_force_t constant_type;
  typedef ::xsd::cxx::tree::sequence< constant_type > constant_sequence;
  typedef constant_sequence::iterator constant_iterator;
  typedef constant_sequence::const_iterator constant_const_iterator;
  typedef ::xsd::cxx::tree::traits< constant_type, char > constant_traits;

  const constant_sequence&
  constant () const;

  constant_sequence&
  constant ();

  void
  constant (const constant_sequence& s);

  // Constructors.
  //
  simulation_force_calculator_t ();

  simulation_force_calculator_t (const ::xercesc::DOMElement& e,
                                 ::xml_schema::flags f = 0,
                                 ::xml_schema::container* c = 0);

  simulation_force_calculator_t (const simulation_force_calculator_t& x,
                                 ::xml_schema::flags f = 0,
                                 ::xml_schema::container* c = 0);

  virtual simulation_force_calculator_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~simulation_force_calculator_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  lennard_jones_sequence lennard_jones_;
  lj_smoothed_sequence lj_smoothed_;
  gravity_sequence gravity_;
  harmonic_sequence harmonic_;
  constant_sequence constant_;
};

class lj_cutoff_t: public ::xml_schema::type
{
  public:
  // cutoff_factor
  // 
  typedef ::xml_schema::double_ cutoff_factor_type;
  typedef ::xsd::cxx::tree::optional< cutoff_factor_type > cutoff_factor_optional;
  typedef ::xsd::cxx::tree::traits< cutoff_factor_type, char, ::xsd::cxx::tree::schema_type::double_ > cutoff_factor_traits;

  const cutoff_factor_optional&
  cutoff_factor () const;

  cutoff_factor_optional&
  cutoff_factor ();

  void
  cutoff_factor (const cutoff_factor_type& x);

  void
  cutoff_factor (const cutoff_factor_optional& x);

  // Constructors.
  //
  lj_cutoff_t ();

  lj_cutoff_t (const ::xercesc::DOMElement& e,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

  lj_cutoff_t (const lj_cutoff_t& x,
               ::xml_schema::flags f = 0,
               ::xml_schema::container* c = 0);

  virtual lj_cutoff_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~lj_cutoff_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  cutoff_factor_optional cutoff_factor_;
};

class lj_smoothed_t: public ::xml_schema::type
{
  public:
  // cutoff_factor
  // 
  typedef ::xml_schema::double_ cutoff_factor_type;
  typedef ::xsd::cxx::tree::traits< cutoff_factor_type, char, ::xsd::cxx::tree::schema_type::double_ > cutoff_factor_traits;

  const cutoff_factor_type&
  cutoff_factor () const;

  cutoff_factor_type&
  cutoff_factor ();

  void
  cutoff_factor (const cutoff_factor_type& x);

  // rl
  // 
  typedef ::xml_schema::double_ rl_type;
  typedef ::xsd::cxx::tree::traits< rl_type, char, ::xsd::cxx::tree::schema_type::double_ > rl_traits;

  const rl_type&
  rl () const;

  rl_type&
  rl ();

  void
  rl (const rl_type& x);

  // Constructors.
  //
  lj_smoothed_t (const cutoff_factor_type&,
                 const rl_type&);

  lj_smoothed_t (const ::xercesc::DOMElement& e,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

  lj_smoothed_t (const lj_smoothed_t& x,
                 ::xml_schema::flags f = 0,
                 ::xml_schema::container* c = 0);

  virtual lj_smoothed_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~lj_smoothed_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< cutoff_factor_type > cutoff_factor_;
  ::xsd::cxx::tree::one< rl_type > rl_;
};

class gravity_t: public ::xml_schema::type
{
  public:
  // g_grav
  // 
  typedef ::xml_schema::double_ g_grav_type;
  typedef ::xsd::cxx::tree::traits< g_grav_type, char, ::xsd::cxx::tree::schema_type::double_ > g_grav_traits;

  const g_grav_type&
  g_grav () const;

  g_grav_type&
  g_grav ();

  void
  g_grav (const g_grav_type& x);

  // direction
  // 
  typedef ::direction_t direction_type;
  typedef ::xsd::cxx::tree::optional< direction_type > direction_optional;
  typedef ::xsd::cxx::tree::traits< direction_type, char > direction_traits;

  const direction_optional&
  direction () const;

  direction_optional&
  direction ();

  void
  direction (const direction_type& x);

  void
  direction (const direction_optional& x);

  void
  direction (::std::auto_ptr< direction_type > p);

  // type
  // 
  typedef ::xml_schema::int_ type_type;
  typedef ::xsd::cxx::tree::optional< type_type > type_optional;
  typedef ::xsd::cxx::tree::traits< type_type, char > type_traits;

  const type_optional&
  type () const;

  type_optional&
  type ();

  void
  type (const type_type& x);

  void
  type (const type_optional& x);

  // Constructors.
  //
  gravity_t (const g_grav_type&);

  gravity_t (const ::xercesc::DOMElement& e,
             ::xml_schema::flags f = 0,
             ::xml_schema::container* c = 0);

  gravity_t (const gravity_t& x,
             ::xml_schema::flags f = 0,
             ::xml_schema::container* c = 0);

  virtual gravity_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~gravity_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< g_grav_type > g_grav_;
  direction_optional direction_;
  type_optional type_;
};

class harmonic_t: public ::xml_schema::type
{
  public:
  // k
  // 
  typedef ::xml_schema::double_ k_type;
  typedef ::xsd::cxx::tree::traits< k_type, char, ::xsd::cxx::tree::schema_type::double_ > k_traits;

  const k_type&
  k () const;

  k_type&
  k ();

  void
  k (const k_type& x);

  // r
  // 
  typedef ::xml_schema::double_ r_type;
  typedef ::xsd::cxx::tree::traits< r_type, char, ::xsd::cxx::tree::schema_type::double_ > r_traits;

  const r_type&
  r () const;

  r_type&
  r ();

  void
  r (const r_type& x);

  // Constructors.
  //
  harmonic_t (const k_type&,
              const r_type&);

  harmonic_t (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

  harmonic_t (const harmonic_t& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

  virtual harmonic_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~harmonic_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< k_type > k_;
  ::xsd::cxx::tree::one< r_type > r_;
};

class constant_force_t: public ::xml_schema::type
{
  public:
  // type
  // 
  typedef ::xml_schema::int_ type_type;
  typedef ::xsd::cxx::tree::traits< type_type, char > type_traits;

  const type_type&
  type () const;

  type_type&
  type ();

  void
  type (const type_type& x);

  // force_x
  // 
  typedef ::xml_schema::double_ force_x_type;
  typedef ::xsd::cxx::tree::traits< force_x_type, char, ::xsd::cxx::tree::schema_type::double_ > force_x_traits;

  const force_x_type&
  force_x () const;

  force_x_type&
  force_x ();

  void
  force_x (const force_x_type& x);

  // force_y
  // 
  typedef ::xml_schema::double_ force_y_type;
  typedef ::xsd::cxx::tree::traits< force_y_type, char, ::xsd::cxx::tree::schema_type::double_ > force_y_traits;

  const force_y_type&
  force_y () const;

  force_y_type&
  force_y ();

  void
  force_y (const force_y_type& x);

  // force_z
  // 
  typedef ::xml_schema::double_ force_z_type;
  typedef ::xsd::cxx::tree::traits< force_z_type, char, ::xsd::cxx::tree::schema_type::double_ > force_z_traits;

  const force_z_type&
  force_z () const;

  force_z_type&
  force_z ();

  void
  force_z (const force_z_type& x);

  // start_time
  // 
  typedef ::xml_schema::double_ start_time_type;
  typedef ::xsd::cxx::tree::optional< start_time_type > start_time_optional;
  typedef ::xsd::cxx::tree::traits< start_time_type, char, ::xsd::cxx::tree::schema_type::double_ > start_time_traits;

  const start_time_optional&
  start_time () const;

  start_time_optional&
  start_time ();

  void
  start_time (const start_time_type& x);

  void
  start_time (const start_time_optional& x);

  // end_time
  // 
  typedef ::xml_schema::double_ end_time_type;
  typedef ::xsd::cxx::tree::optional< end_time_type > end_time_optional;
  typedef ::xsd::cxx::tree::traits< end_time_type, char, ::xsd::cxx::tree::schema_type::double_ > end_time_traits;

  const end_time_optional&
  end_time () const;

  end_time_optional&
  end_time ();

  void
  end_time (const end_time_type& x);

  void
  end_time (const end_time_optional& x);

  // Constructors.
  //
  constant_force_t (const type_type&,
                    const force_x_type&,
                    const force_y_type&,
                    const force_z_type&);

  constant_force_t (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

  constant_force_t (const constant_force_t& x,
                    ::xml_schema::flags f = 0,
                    ::xml_schema::container* c = 0);

  virtual constant_force_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~constant_force_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< type_type > type_;
  ::xsd::cxx::tree::one< force_x_type > force_x_;
  ::xsd::cxx::tree::one< force_y_type > force_y_;
  ::xsd::cxx::tree::one< force_z_type > force_z_;
  start_time_optional start_time_;
  end_time_optional end_time_;
};

class simulation_mode_t: public ::xml_schema::type
{
  public:
  // type
  // 
  typedef ::simulation_mode_type_t type_type;
  typedef ::xsd::cxx::tree::traits< type_type, char > type_traits;

  const type_type&
  type () const;

  type_type&
  type ();

  void
  type (const type_type& x);

  void
  type (::std::auto_ptr< type_type > p);

  // cutoff_radius
  // 
  typedef ::xml_schema::double_ cutoff_radius_type;
  typedef ::xsd::cxx::tree::optional< cutoff_radius_type > cutoff_radius_optional;
  typedef ::xsd::cxx::tree::traits< cutoff_radius_type, char, ::xsd::cxx::tree::schema_type::double_ > cutoff_radius_traits;

  const cutoff_radius_optional&
  cutoff_radius () const;

  cutoff_radius_optional&
  cutoff_radius ();

  void
  cutoff_radius (const cutoff_radius_type& x);

  void
  cutoff_radius (const cutoff_radius_optional& x);

  // domain_size_x
  // 
  typedef ::xml_schema::double_ domain_size_x_type;
  typedef ::xsd::cxx::tree::optional< domain_size_x_type > domain_size_x_optional;
  typedef ::xsd::cxx::tree::traits< domain_size_x_type, char, ::xsd::cxx::tree::schema_type::double_ > domain_size_x_traits;

  const domain_size_x_optional&
  domain_size_x () const;

  domain_size_x_optional&
  domain_size_x ();

  void
  domain_size_x (const domain_size_x_type& x);

  void
  domain_size_x (const domain_size_x_optional& x);

  // domain_size_y
  // 
  typedef ::xml_schema::double_ domain_size_y_type;
  typedef ::xsd::cxx::tree::optional< domain_size_y_type > domain_size_y_optional;
  typedef ::xsd::cxx::tree::traits< domain_size_y_type, char, ::xsd::cxx::tree::schema_type::double_ > domain_size_y_traits;

  const domain_size_y_optional&
  domain_size_y () const;

  domain_size_y_optional&
  domain_size_y ();

  void
  domain_size_y (const domain_size_y_type& x);

  void
  domain_size_y (const domain_size_y_optional& x);

  // domain_size_z
  // 
  typedef ::xml_schema::double_ domain_size_z_type;
  typedef ::xsd::cxx::tree::optional< domain_size_z_type > domain_size_z_optional;
  typedef ::xsd::cxx::tree::traits< domain_size_z_type, char, ::xsd::cxx::tree::schema_type::double_ > domain_size_z_traits;

  const domain_size_z_optional&
  domain_size_z () const;

  domain_size_z_optional&
  domain_size_z ();

  void
  domain_size_z (const domain_size_z_type& x);

  void
  domain_size_z (const domain_size_z_optional& x);

  // boundary
  // 
  typedef ::boundary_t boundary_type;
  typedef ::xsd::cxx::tree::optional< boundary_type > boundary_optional;
  typedef ::xsd::cxx::tree::traits< boundary_type, char > boundary_traits;

  const boundary_optional&
  boundary () const;

  boundary_optional&
  boundary ();

  void
  boundary (const boundary_type& x);

  void
  boundary (const boundary_optional& x);

  void
  boundary (::std::auto_ptr< boundary_type > p);

  // Constructors.
  //
  simulation_mode_t (const type_type&);

  simulation_mode_t (const ::xercesc::DOMElement& e,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

  simulation_mode_t (const simulation_mode_t& x,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

  virtual simulation_mode_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~simulation_mode_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< type_type > type_;
  cutoff_radius_optional cutoff_radius_;
  domain_size_x_optional domain_size_x_;
  domain_size_y_optional domain_size_y_;
  domain_size_z_optional domain_size_z_;
  boundary_optional boundary_;
};

class thermostat_t: public ::xml_schema::type
{
  public:
  // dim
  // 
  typedef ::xml_schema::unsigned_int dim_type;
  typedef ::xsd::cxx::tree::traits< dim_type, char > dim_traits;

  const dim_type&
  dim () const;

  dim_type&
  dim ();

  void
  dim (const dim_type& x);

  // init_temp
  // 
  typedef ::xml_schema::double_ init_temp_type;
  typedef ::xsd::cxx::tree::traits< init_temp_type, char, ::xsd::cxx::tree::schema_type::double_ > init_temp_traits;

  const init_temp_type&
  init_temp () const;

  init_temp_type&
  init_temp ();

  void
  init_temp (const init_temp_type& x);

  // steps
  // 
  typedef ::xml_schema::unsigned_int steps_type;
  typedef ::xsd::cxx::tree::traits< steps_type, char > steps_traits;

  const steps_type&
  steps () const;

  steps_type&
  steps ();

  void
  steps (const steps_type& x);

  // target_temp
  // 
  typedef ::xml_schema::double_ target_temp_type;
  typedef ::xsd::cxx::tree::optional< target_temp_type > target_temp_optional;
  typedef ::xsd::cxx::tree::traits< target_temp_type, char, ::xsd::cxx::tree::schema_type::double_ > target_temp_traits;

  const target_temp_optional&
  target_temp () const;

  target_temp_optional&
  target_temp ();

  void
  target_temp (const target_temp_type& x);

  void
  target_temp (const target_temp_optional& x);

  // delta_temp
  // 
  typedef ::xml_schema::double_ delta_temp_type;
  typedef ::xsd::cxx::tree::optional< delta_temp_type > delta_temp_optional;
  typedef ::xsd::cxx::tree::traits< delta_temp_type, char, ::xsd::cxx::tree::schema_type::double_ > delta_temp_traits;

  const delta_temp_optional&
  delta_temp () const;

  delta_temp_optional&
  delta_temp ();

  void
  delta_temp (const delta_temp_type& x);

  void
  delta_temp (const delta_temp_optional& x);

  // steps_changetemp
  // 
  typedef ::xml_schema::unsigned_int steps_changetemp_type;
  typedef ::xsd::cxx::tree::optional< steps_changetemp_type > steps_changetemp_optional;
  typedef ::xsd::cxx::tree::traits< steps_changetemp_type, char > steps_changetemp_traits;

  const steps_changetemp_optional&
  steps_changetemp () const;

  steps_changetemp_optional&
  steps_changetemp ();

  void
  steps_changetemp (const steps_changetemp_type& x);

  void
  steps_changetemp (const steps_changetemp_optional& x);

  // apply_brown
  // 
  typedef ::xml_schema::boolean apply_brown_type;
  typedef ::xsd::cxx::tree::optional< apply_brown_type > apply_brown_optional;
  typedef ::xsd::cxx::tree::traits< apply_brown_type, char > apply_brown_traits;

  const apply_brown_optional&
  apply_brown () const;

  apply_brown_optional&
  apply_brown ();

  void
  apply_brown (const apply_brown_type& x);

  void
  apply_brown (const apply_brown_optional& x);

  // direction
  // 
  typedef ::xml_schema::int_ direction_type;
  typedef ::xsd::cxx::tree::optional< direction_type > direction_optional;
  typedef ::xsd::cxx::tree::traits< direction_type, char > direction_traits;

  const direction_optional&
  direction () const;

  direction_optional&
  direction ();

  void
  direction (const direction_type& x);

  void
  direction (const direction_optional& x);

  // type
  // 
  typedef ::xml_schema::int_ type_type;
  typedef ::xsd::cxx::tree::optional< type_type > type_optional;
  typedef ::xsd::cxx::tree::traits< type_type, char > type_traits;

  const type_optional&
  type () const;

  type_optional&
  type ();

  void
  type (const type_type& x);

  void
  type (const type_optional& x);

  // Constructors.
  //
  thermostat_t (const dim_type&,
                const init_temp_type&,
                const steps_type&);

  thermostat_t (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

  thermostat_t (const thermostat_t& x,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

  virtual thermostat_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~thermostat_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< dim_type > dim_;
  ::xsd::cxx::tree::one< init_temp_type > init_temp_;
  ::xsd::cxx::tree::one< steps_type > steps_;
  target_temp_optional target_temp_;
  delta_temp_optional delta_temp_;
  steps_changetemp_optional steps_changetemp_;
  apply_brown_optional apply_brown_;
  direction_optional direction_;
  type_optional type_;
};

class thermodyn_stats_t: public ::xml_schema::type
{
  public:
  // freq
  // 
  typedef ::xml_schema::unsigned_int freq_type;
  typedef ::xsd::cxx::tree::traits< freq_type, char > freq_traits;

  const freq_type&
  freq () const;

  freq_type&
  freq ();

  void
  freq (const freq_type& x);

  // avgover
  // 
  typedef ::xml_schema::unsigned_int avgover_type;
  typedef ::xsd::cxx::tree::traits< avgover_type, char > avgover_traits;

  const avgover_type&
  avgover () const;

  avgover_type&
  avgover ();

  void
  avgover (const avgover_type& x);

  // dr
  // 
  typedef ::xml_schema::double_ dr_type;
  typedef ::xsd::cxx::tree::traits< dr_type, char, ::xsd::cxx::tree::schema_type::double_ > dr_traits;

  const dr_type&
  dr () const;

  dr_type&
  dr ();

  void
  dr (const dr_type& x);

  // maxrad
  // 
  typedef ::xml_schema::double_ maxrad_type;
  typedef ::xsd::cxx::tree::traits< maxrad_type, char, ::xsd::cxx::tree::schema_type::double_ > maxrad_traits;

  const maxrad_type&
  maxrad () const;

  maxrad_type&
  maxrad ();

  void
  maxrad (const maxrad_type& x);

  // varfile
  // 
  typedef ::xml_schema::string varfile_type;
  typedef ::xsd::cxx::tree::traits< varfile_type, char > varfile_traits;

  const varfile_type&
  varfile () const;

  varfile_type&
  varfile ();

  void
  varfile (const varfile_type& x);

  void
  varfile (::std::auto_ptr< varfile_type > p);

  // rdffile
  // 
  typedef ::xml_schema::string rdffile_type;
  typedef ::xsd::cxx::tree::traits< rdffile_type, char > rdffile_traits;

  const rdffile_type&
  rdffile () const;

  rdffile_type&
  rdffile ();

  void
  rdffile (const rdffile_type& x);

  void
  rdffile (::std::auto_ptr< rdffile_type > p);

  // Constructors.
  //
  thermodyn_stats_t (const freq_type&,
                     const avgover_type&,
                     const dr_type&,
                     const maxrad_type&,
                     const varfile_type&,
                     const rdffile_type&);

  thermodyn_stats_t (const ::xercesc::DOMElement& e,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

  thermodyn_stats_t (const thermodyn_stats_t& x,
                     ::xml_schema::flags f = 0,
                     ::xml_schema::container* c = 0);

  virtual thermodyn_stats_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~thermodyn_stats_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< freq_type > freq_;
  ::xsd::cxx::tree::one< avgover_type > avgover_;
  ::xsd::cxx::tree::one< dr_type > dr_;
  ::xsd::cxx::tree::one< maxrad_type > maxrad_;
  ::xsd::cxx::tree::one< varfile_type > varfile_;
  ::xsd::cxx::tree::one< rdffile_type > rdffile_;
};

class fixed_t: public ::xml_schema::simple_type,
  public ::xsd::cxx::tree::list< ::xml_schema::int_, char >
{
  public:
  fixed_t ();

  fixed_t (size_type n, const ::xml_schema::int_& x);

  template < typename I >
  fixed_t (const I& begin, const I& end)
  : ::xsd::cxx::tree::list< ::xml_schema::int_, char > (begin, end, this)
  {
  }

  fixed_t (const ::xercesc::DOMElement& e,
           ::xml_schema::flags f = 0,
           ::xml_schema::container* c = 0);

  fixed_t (const ::xercesc::DOMAttr& a,
           ::xml_schema::flags f = 0,
           ::xml_schema::container* c = 0);

  fixed_t (const ::std::string& s,
           const ::xercesc::DOMElement* e,
           ::xml_schema::flags f = 0,
           ::xml_schema::container* c = 0);

  fixed_t (const fixed_t& x,
           ::xml_schema::flags f = 0,
           ::xml_schema::container* c = 0);

  virtual fixed_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~fixed_t ();
};

class veldenprof_t: public ::xml_schema::type
{
  public:
  // x_start
  // 
  typedef ::xml_schema::double_ x_start_type;
  typedef ::xsd::cxx::tree::traits< x_start_type, char, ::xsd::cxx::tree::schema_type::double_ > x_start_traits;

  const x_start_type&
  x_start () const;

  x_start_type&
  x_start ();

  void
  x_start (const x_start_type& x);

  // x_end
  // 
  typedef ::xml_schema::double_ x_end_type;
  typedef ::xsd::cxx::tree::traits< x_end_type, char, ::xsd::cxx::tree::schema_type::double_ > x_end_traits;

  const x_end_type&
  x_end () const;

  x_end_type&
  x_end ();

  void
  x_end (const x_end_type& x);

  // x_count
  // 
  typedef ::xml_schema::unsigned_int x_count_type;
  typedef ::xsd::cxx::tree::traits< x_count_type, char > x_count_traits;

  const x_count_type&
  x_count () const;

  x_count_type&
  x_count ();

  void
  x_count (const x_count_type& x);

  // file
  // 
  typedef ::xml_schema::string file_type;
  typedef ::xsd::cxx::tree::traits< file_type, char > file_traits;

  const file_type&
  file () const;

  file_type&
  file ();

  void
  file (const file_type& x);

  void
  file (::std::auto_ptr< file_type > p);

  // freq
  // 
  typedef ::xml_schema::unsigned_int freq_type;
  typedef ::xsd::cxx::tree::traits< freq_type, char > freq_traits;

  const freq_type&
  freq () const;

  freq_type&
  freq ();

  void
  freq (const freq_type& x);

  // Constructors.
  //
  veldenprof_t (const x_start_type&,
                const x_end_type&,
                const x_count_type&,
                const file_type&,
                const freq_type&);

  veldenprof_t (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

  veldenprof_t (const veldenprof_t& x,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

  virtual veldenprof_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~veldenprof_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< x_start_type > x_start_;
  ::xsd::cxx::tree::one< x_end_type > x_end_;
  ::xsd::cxx::tree::one< x_count_type > x_count_;
  ::xsd::cxx::tree::one< file_type > file_;
  ::xsd::cxx::tree::one< freq_type > freq_;
};

class simulation_parameters_t: public ::xml_schema::type
{
  public:
  // start-time
  // 
  typedef ::xml_schema::double_ start_time_type;
  typedef ::xsd::cxx::tree::traits< start_time_type, char, ::xsd::cxx::tree::schema_type::double_ > start_time_traits;

  const start_time_type&
  start_time () const;

  start_time_type&
  start_time ();

  void
  start_time (const start_time_type& x);

  // end-time
  // 
  typedef ::xml_schema::double_ end_time_type;
  typedef ::xsd::cxx::tree::traits< end_time_type, char, ::xsd::cxx::tree::schema_type::double_ > end_time_traits;

  const end_time_type&
  end_time () const;

  end_time_type&
  end_time ();

  void
  end_time (const end_time_type& x);

  // delta-t
  // 
  typedef ::xml_schema::double_ delta_t_type;
  typedef ::xsd::cxx::tree::traits< delta_t_type, char, ::xsd::cxx::tree::schema_type::double_ > delta_t_traits;

  const delta_t_type&
  delta_t () const;

  delta_t_type&
  delta_t ();

  void
  delta_t (const delta_t_type& x);

  // simulation-mode
  // 
  typedef ::simulation_mode_t simulation_mode_type;
  typedef ::xsd::cxx::tree::traits< simulation_mode_type, char > simulation_mode_traits;

  const simulation_mode_type&
  simulation_mode () const;

  simulation_mode_type&
  simulation_mode ();

  void
  simulation_mode (const simulation_mode_type& x);

  void
  simulation_mode (::std::auto_ptr< simulation_mode_type > p);

  // thermostat
  // 
  typedef ::thermostat_t thermostat_type;
  typedef ::xsd::cxx::tree::optional< thermostat_type > thermostat_optional;
  typedef ::xsd::cxx::tree::traits< thermostat_type, char > thermostat_traits;

  const thermostat_optional&
  thermostat () const;

  thermostat_optional&
  thermostat ();

  void
  thermostat (const thermostat_type& x);

  void
  thermostat (const thermostat_optional& x);

  void
  thermostat (::std::auto_ptr< thermostat_type > p);

  // thermodyn-stats
  // 
  typedef ::thermodyn_stats_t thermodyn_stats_type;
  typedef ::xsd::cxx::tree::optional< thermodyn_stats_type > thermodyn_stats_optional;
  typedef ::xsd::cxx::tree::traits< thermodyn_stats_type, char > thermodyn_stats_traits;

  const thermodyn_stats_optional&
  thermodyn_stats () const;

  thermodyn_stats_optional&
  thermodyn_stats ();

  void
  thermodyn_stats (const thermodyn_stats_type& x);

  void
  thermodyn_stats (const thermodyn_stats_optional& x);

  void
  thermodyn_stats (::std::auto_ptr< thermodyn_stats_type > p);

  // fixed
  // 
  typedef ::fixed_t fixed_type;
  typedef ::xsd::cxx::tree::optional< fixed_type > fixed_optional;
  typedef ::xsd::cxx::tree::traits< fixed_type, char > fixed_traits;

  const fixed_optional&
  fixed () const;

  fixed_optional&
  fixed ();

  void
  fixed (const fixed_type& x);

  void
  fixed (const fixed_optional& x);

  void
  fixed (::std::auto_ptr< fixed_type > p);

  // velocity-density-profile
  // 
  typedef ::veldenprof_t velocity_density_profile_type;
  typedef ::xsd::cxx::tree::optional< velocity_density_profile_type > velocity_density_profile_optional;
  typedef ::xsd::cxx::tree::traits< velocity_density_profile_type, char > velocity_density_profile_traits;

  const velocity_density_profile_optional&
  velocity_density_profile () const;

  velocity_density_profile_optional&
  velocity_density_profile ();

  void
  velocity_density_profile (const velocity_density_profile_type& x);

  void
  velocity_density_profile (const velocity_density_profile_optional& x);

  void
  velocity_density_profile (::std::auto_ptr< velocity_density_profile_type > p);

  // Constructors.
  //
  simulation_parameters_t (const start_time_type&,
                           const end_time_type&,
                           const delta_t_type&,
                           const simulation_mode_type&);

  simulation_parameters_t (const start_time_type&,
                           const end_time_type&,
                           const delta_t_type&,
                           ::std::auto_ptr< simulation_mode_type >&);

  simulation_parameters_t (const ::xercesc::DOMElement& e,
                           ::xml_schema::flags f = 0,
                           ::xml_schema::container* c = 0);

  simulation_parameters_t (const simulation_parameters_t& x,
                           ::xml_schema::flags f = 0,
                           ::xml_schema::container* c = 0);

  virtual simulation_parameters_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~simulation_parameters_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< start_time_type > start_time_;
  ::xsd::cxx::tree::one< end_time_type > end_time_;
  ::xsd::cxx::tree::one< delta_t_type > delta_t_;
  ::xsd::cxx::tree::one< simulation_mode_type > simulation_mode_;
  thermostat_optional thermostat_;
  thermodyn_stats_optional thermodyn_stats_;
  fixed_optional fixed_;
  velocity_density_profile_optional velocity_density_profile_;
};

class cuboid_t: public ::xml_schema::type
{
  public:
  // x1
  // 
  typedef ::xml_schema::double_ x1_type;
  typedef ::xsd::cxx::tree::traits< x1_type, char, ::xsd::cxx::tree::schema_type::double_ > x1_traits;

  const x1_type&
  x1 () const;

  x1_type&
  x1 ();

  void
  x1 (const x1_type& x);

  // x2
  // 
  typedef ::xml_schema::double_ x2_type;
  typedef ::xsd::cxx::tree::traits< x2_type, char, ::xsd::cxx::tree::schema_type::double_ > x2_traits;

  const x2_type&
  x2 () const;

  x2_type&
  x2 ();

  void
  x2 (const x2_type& x);

  // x3
  // 
  typedef ::xml_schema::double_ x3_type;
  typedef ::xsd::cxx::tree::traits< x3_type, char, ::xsd::cxx::tree::schema_type::double_ > x3_traits;

  const x3_type&
  x3 () const;

  x3_type&
  x3 ();

  void
  x3 (const x3_type& x);

  // n1
  // 
  typedef ::xml_schema::unsigned_int n1_type;
  typedef ::xsd::cxx::tree::traits< n1_type, char > n1_traits;

  const n1_type&
  n1 () const;

  n1_type&
  n1 ();

  void
  n1 (const n1_type& x);

  // n2
  // 
  typedef ::xml_schema::unsigned_int n2_type;
  typedef ::xsd::cxx::tree::traits< n2_type, char > n2_traits;

  const n2_type&
  n2 () const;

  n2_type&
  n2 ();

  void
  n2 (const n2_type& x);

  // n3
  // 
  typedef ::xml_schema::unsigned_int n3_type;
  typedef ::xsd::cxx::tree::traits< n3_type, char > n3_traits;

  const n3_type&
  n3 () const;

  n3_type&
  n3 ();

  void
  n3 (const n3_type& x);

  // h
  // 
  typedef ::xml_schema::double_ h_type;
  typedef ::xsd::cxx::tree::traits< h_type, char, ::xsd::cxx::tree::schema_type::double_ > h_traits;

  const h_type&
  h () const;

  h_type&
  h ();

  void
  h (const h_type& x);

  // m
  // 
  typedef ::xml_schema::double_ m_type;
  typedef ::xsd::cxx::tree::traits< m_type, char, ::xsd::cxx::tree::schema_type::double_ > m_traits;

  const m_type&
  m () const;

  m_type&
  m ();

  void
  m (const m_type& x);

  // epsilon
  // 
  typedef ::xml_schema::double_ epsilon_type;
  typedef ::xsd::cxx::tree::traits< epsilon_type, char, ::xsd::cxx::tree::schema_type::double_ > epsilon_traits;

  const epsilon_type&
  epsilon () const;

  epsilon_type&
  epsilon ();

  void
  epsilon (const epsilon_type& x);

  // sigma
  // 
  typedef ::xml_schema::double_ sigma_type;
  typedef ::xsd::cxx::tree::traits< sigma_type, char, ::xsd::cxx::tree::schema_type::double_ > sigma_traits;

  const sigma_type&
  sigma () const;

  sigma_type&
  sigma ();

  void
  sigma (const sigma_type& x);

  // type
  // 
  typedef ::xml_schema::int_ type_type;
  typedef ::xsd::cxx::tree::traits< type_type, char > type_traits;

  const type_type&
  type () const;

  type_type&
  type ();

  void
  type (const type_type& x);

  // v1
  // 
  typedef ::xml_schema::double_ v1_type;
  typedef ::xsd::cxx::tree::traits< v1_type, char, ::xsd::cxx::tree::schema_type::double_ > v1_traits;

  const v1_type&
  v1 () const;

  v1_type&
  v1 ();

  void
  v1 (const v1_type& x);

  // v2
  // 
  typedef ::xml_schema::double_ v2_type;
  typedef ::xsd::cxx::tree::traits< v2_type, char, ::xsd::cxx::tree::schema_type::double_ > v2_traits;

  const v2_type&
  v2 () const;

  v2_type&
  v2 ();

  void
  v2 (const v2_type& x);

  // v3
  // 
  typedef ::xml_schema::double_ v3_type;
  typedef ::xsd::cxx::tree::traits< v3_type, char, ::xsd::cxx::tree::schema_type::double_ > v3_traits;

  const v3_type&
  v3 () const;

  v3_type&
  v3 ();

  void
  v3 (const v3_type& x);

  // Constructors.
  //
  cuboid_t (const x1_type&,
            const x2_type&,
            const x3_type&,
            const n1_type&,
            const n2_type&,
            const n3_type&,
            const h_type&,
            const m_type&,
            const epsilon_type&,
            const sigma_type&,
            const type_type&,
            const v1_type&,
            const v2_type&,
            const v3_type&);

  cuboid_t (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

  cuboid_t (const cuboid_t& x,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

  virtual cuboid_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~cuboid_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< x1_type > x1_;
  ::xsd::cxx::tree::one< x2_type > x2_;
  ::xsd::cxx::tree::one< x3_type > x3_;
  ::xsd::cxx::tree::one< n1_type > n1_;
  ::xsd::cxx::tree::one< n2_type > n2_;
  ::xsd::cxx::tree::one< n3_type > n3_;
  ::xsd::cxx::tree::one< h_type > h_;
  ::xsd::cxx::tree::one< m_type > m_;
  ::xsd::cxx::tree::one< epsilon_type > epsilon_;
  ::xsd::cxx::tree::one< sigma_type > sigma_;
  ::xsd::cxx::tree::one< type_type > type_;
  ::xsd::cxx::tree::one< v1_type > v1_;
  ::xsd::cxx::tree::one< v2_type > v2_;
  ::xsd::cxx::tree::one< v3_type > v3_;
};

class sphere_t: public ::xml_schema::type
{
  public:
  // x1
  // 
  typedef ::xml_schema::double_ x1_type;
  typedef ::xsd::cxx::tree::traits< x1_type, char, ::xsd::cxx::tree::schema_type::double_ > x1_traits;

  const x1_type&
  x1 () const;

  x1_type&
  x1 ();

  void
  x1 (const x1_type& x);

  // x2
  // 
  typedef ::xml_schema::double_ x2_type;
  typedef ::xsd::cxx::tree::traits< x2_type, char, ::xsd::cxx::tree::schema_type::double_ > x2_traits;

  const x2_type&
  x2 () const;

  x2_type&
  x2 ();

  void
  x2 (const x2_type& x);

  // x3
  // 
  typedef ::xml_schema::double_ x3_type;
  typedef ::xsd::cxx::tree::traits< x3_type, char, ::xsd::cxx::tree::schema_type::double_ > x3_traits;

  const x3_type&
  x3 () const;

  x3_type&
  x3 ();

  void
  x3 (const x3_type& x);

  // r
  // 
  typedef ::xml_schema::unsigned_int r_type;
  typedef ::xsd::cxx::tree::traits< r_type, char > r_traits;

  const r_type&
  r () const;

  r_type&
  r ();

  void
  r (const r_type& x);

  // h
  // 
  typedef ::xml_schema::double_ h_type;
  typedef ::xsd::cxx::tree::traits< h_type, char, ::xsd::cxx::tree::schema_type::double_ > h_traits;

  const h_type&
  h () const;

  h_type&
  h ();

  void
  h (const h_type& x);

  // m
  // 
  typedef ::xml_schema::double_ m_type;
  typedef ::xsd::cxx::tree::traits< m_type, char, ::xsd::cxx::tree::schema_type::double_ > m_traits;

  const m_type&
  m () const;

  m_type&
  m ();

  void
  m (const m_type& x);

  // epsilon
  // 
  typedef ::xml_schema::double_ epsilon_type;
  typedef ::xsd::cxx::tree::traits< epsilon_type, char, ::xsd::cxx::tree::schema_type::double_ > epsilon_traits;

  const epsilon_type&
  epsilon () const;

  epsilon_type&
  epsilon ();

  void
  epsilon (const epsilon_type& x);

  // sigma
  // 
  typedef ::xml_schema::double_ sigma_type;
  typedef ::xsd::cxx::tree::traits< sigma_type, char, ::xsd::cxx::tree::schema_type::double_ > sigma_traits;

  const sigma_type&
  sigma () const;

  sigma_type&
  sigma ();

  void
  sigma (const sigma_type& x);

  // type
  // 
  typedef ::xml_schema::int_ type_type;
  typedef ::xsd::cxx::tree::traits< type_type, char > type_traits;

  const type_type&
  type () const;

  type_type&
  type ();

  void
  type (const type_type& x);

  // v1
  // 
  typedef ::xml_schema::double_ v1_type;
  typedef ::xsd::cxx::tree::traits< v1_type, char, ::xsd::cxx::tree::schema_type::double_ > v1_traits;

  const v1_type&
  v1 () const;

  v1_type&
  v1 ();

  void
  v1 (const v1_type& x);

  // v2
  // 
  typedef ::xml_schema::double_ v2_type;
  typedef ::xsd::cxx::tree::traits< v2_type, char, ::xsd::cxx::tree::schema_type::double_ > v2_traits;

  const v2_type&
  v2 () const;

  v2_type&
  v2 ();

  void
  v2 (const v2_type& x);

  // v3
  // 
  typedef ::xml_schema::double_ v3_type;
  typedef ::xsd::cxx::tree::traits< v3_type, char, ::xsd::cxx::tree::schema_type::double_ > v3_traits;

  const v3_type&
  v3 () const;

  v3_type&
  v3 ();

  void
  v3 (const v3_type& x);

  // Constructors.
  //
  sphere_t (const x1_type&,
            const x2_type&,
            const x3_type&,
            const r_type&,
            const h_type&,
            const m_type&,
            const epsilon_type&,
            const sigma_type&,
            const type_type&,
            const v1_type&,
            const v2_type&,
            const v3_type&);

  sphere_t (const ::xercesc::DOMElement& e,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

  sphere_t (const sphere_t& x,
            ::xml_schema::flags f = 0,
            ::xml_schema::container* c = 0);

  virtual sphere_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~sphere_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< x1_type > x1_;
  ::xsd::cxx::tree::one< x2_type > x2_;
  ::xsd::cxx::tree::one< x3_type > x3_;
  ::xsd::cxx::tree::one< r_type > r_;
  ::xsd::cxx::tree::one< h_type > h_;
  ::xsd::cxx::tree::one< m_type > m_;
  ::xsd::cxx::tree::one< epsilon_type > epsilon_;
  ::xsd::cxx::tree::one< sigma_type > sigma_;
  ::xsd::cxx::tree::one< type_type > type_;
  ::xsd::cxx::tree::one< v1_type > v1_;
  ::xsd::cxx::tree::one< v2_type > v2_;
  ::xsd::cxx::tree::one< v3_type > v3_;
};

class membrane_t: public ::xml_schema::type
{
  public:
  // x1
  // 
  typedef ::xml_schema::double_ x1_type;
  typedef ::xsd::cxx::tree::traits< x1_type, char, ::xsd::cxx::tree::schema_type::double_ > x1_traits;

  const x1_type&
  x1 () const;

  x1_type&
  x1 ();

  void
  x1 (const x1_type& x);

  // x2
  // 
  typedef ::xml_schema::double_ x2_type;
  typedef ::xsd::cxx::tree::traits< x2_type, char, ::xsd::cxx::tree::schema_type::double_ > x2_traits;

  const x2_type&
  x2 () const;

  x2_type&
  x2 ();

  void
  x2 (const x2_type& x);

  // x3
  // 
  typedef ::xml_schema::double_ x3_type;
  typedef ::xsd::cxx::tree::traits< x3_type, char, ::xsd::cxx::tree::schema_type::double_ > x3_traits;

  const x3_type&
  x3 () const;

  x3_type&
  x3 ();

  void
  x3 (const x3_type& x);

  // n1
  // 
  typedef ::xml_schema::unsigned_int n1_type;
  typedef ::xsd::cxx::tree::traits< n1_type, char > n1_traits;

  const n1_type&
  n1 () const;

  n1_type&
  n1 ();

  void
  n1 (const n1_type& x);

  // n2
  // 
  typedef ::xml_schema::unsigned_int n2_type;
  typedef ::xsd::cxx::tree::traits< n2_type, char > n2_traits;

  const n2_type&
  n2 () const;

  n2_type&
  n2 ();

  void
  n2 (const n2_type& x);

  // n3
  // 
  typedef ::xml_schema::unsigned_int n3_type;
  typedef ::xsd::cxx::tree::traits< n3_type, char > n3_traits;

  const n3_type&
  n3 () const;

  n3_type&
  n3 ();

  void
  n3 (const n3_type& x);

  // h
  // 
  typedef ::xml_schema::double_ h_type;
  typedef ::xsd::cxx::tree::traits< h_type, char, ::xsd::cxx::tree::schema_type::double_ > h_traits;

  const h_type&
  h () const;

  h_type&
  h ();

  void
  h (const h_type& x);

  // m
  // 
  typedef ::xml_schema::double_ m_type;
  typedef ::xsd::cxx::tree::traits< m_type, char, ::xsd::cxx::tree::schema_type::double_ > m_traits;

  const m_type&
  m () const;

  m_type&
  m ();

  void
  m (const m_type& x);

  // epsilon
  // 
  typedef ::xml_schema::double_ epsilon_type;
  typedef ::xsd::cxx::tree::traits< epsilon_type, char, ::xsd::cxx::tree::schema_type::double_ > epsilon_traits;

  const epsilon_type&
  epsilon () const;

  epsilon_type&
  epsilon ();

  void
  epsilon (const epsilon_type& x);

  // sigma
  // 
  typedef ::xml_schema::double_ sigma_type;
  typedef ::xsd::cxx::tree::traits< sigma_type, char, ::xsd::cxx::tree::schema_type::double_ > sigma_traits;

  const sigma_type&
  sigma () const;

  sigma_type&
  sigma ();

  void
  sigma (const sigma_type& x);

  // type
  // 
  typedef ::xml_schema::int_ type_type;
  typedef ::xsd::cxx::tree::traits< type_type, char > type_traits;

  const type_type&
  type () const;

  type_type&
  type ();

  void
  type (const type_type& x);

  // v1
  // 
  typedef ::xml_schema::double_ v1_type;
  typedef ::xsd::cxx::tree::traits< v1_type, char, ::xsd::cxx::tree::schema_type::double_ > v1_traits;

  const v1_type&
  v1 () const;

  v1_type&
  v1 ();

  void
  v1 (const v1_type& x);

  // v2
  // 
  typedef ::xml_schema::double_ v2_type;
  typedef ::xsd::cxx::tree::traits< v2_type, char, ::xsd::cxx::tree::schema_type::double_ > v2_traits;

  const v2_type&
  v2 () const;

  v2_type&
  v2 ();

  void
  v2 (const v2_type& x);

  // v3
  // 
  typedef ::xml_schema::double_ v3_type;
  typedef ::xsd::cxx::tree::traits< v3_type, char, ::xsd::cxx::tree::schema_type::double_ > v3_traits;

  const v3_type&
  v3 () const;

  v3_type&
  v3 ();

  void
  v3 (const v3_type& x);

  // mark_type
  // 
  typedef ::xml_schema::int_ mark_type_type;
  typedef ::xsd::cxx::tree::optional< mark_type_type > mark_type_optional;
  typedef ::xsd::cxx::tree::traits< mark_type_type, char > mark_type_traits;

  const mark_type_optional&
  mark_type () const;

  mark_type_optional&
  mark_type ();

  void
  mark_type (const mark_type_type& x);

  void
  mark_type (const mark_type_optional& x);

  // mark_x
  // 
  typedef ::xml_schema::unsigned_int mark_x_type;
  typedef ::xsd::cxx::tree::optional< mark_x_type > mark_x_optional;
  typedef ::xsd::cxx::tree::traits< mark_x_type, char > mark_x_traits;

  const mark_x_optional&
  mark_x () const;

  mark_x_optional&
  mark_x ();

  void
  mark_x (const mark_x_type& x);

  void
  mark_x (const mark_x_optional& x);

  // mark_y
  // 
  typedef ::xml_schema::unsigned_int mark_y_type;
  typedef ::xsd::cxx::tree::optional< mark_y_type > mark_y_optional;
  typedef ::xsd::cxx::tree::traits< mark_y_type, char > mark_y_traits;

  const mark_y_optional&
  mark_y () const;

  mark_y_optional&
  mark_y ();

  void
  mark_y (const mark_y_type& x);

  void
  mark_y (const mark_y_optional& x);

  // Constructors.
  //
  membrane_t (const x1_type&,
              const x2_type&,
              const x3_type&,
              const n1_type&,
              const n2_type&,
              const n3_type&,
              const h_type&,
              const m_type&,
              const epsilon_type&,
              const sigma_type&,
              const type_type&,
              const v1_type&,
              const v2_type&,
              const v3_type&);

  membrane_t (const ::xercesc::DOMElement& e,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

  membrane_t (const membrane_t& x,
              ::xml_schema::flags f = 0,
              ::xml_schema::container* c = 0);

  virtual membrane_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~membrane_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< x1_type > x1_;
  ::xsd::cxx::tree::one< x2_type > x2_;
  ::xsd::cxx::tree::one< x3_type > x3_;
  ::xsd::cxx::tree::one< n1_type > n1_;
  ::xsd::cxx::tree::one< n2_type > n2_;
  ::xsd::cxx::tree::one< n3_type > n3_;
  ::xsd::cxx::tree::one< h_type > h_;
  ::xsd::cxx::tree::one< m_type > m_;
  ::xsd::cxx::tree::one< epsilon_type > epsilon_;
  ::xsd::cxx::tree::one< sigma_type > sigma_;
  ::xsd::cxx::tree::one< type_type > type_;
  ::xsd::cxx::tree::one< v1_type > v1_;
  ::xsd::cxx::tree::one< v2_type > v2_;
  ::xsd::cxx::tree::one< v3_type > v3_;
  mark_type_optional mark_type_;
  mark_x_optional mark_x_;
  mark_y_optional mark_y_;
};

class simulation_input_t: public ::xml_schema::type
{
  public:
  // particle_file
  // 
  typedef ::xml_schema::string particle_file_type;
  typedef ::xsd::cxx::tree::sequence< particle_file_type > particle_file_sequence;
  typedef particle_file_sequence::iterator particle_file_iterator;
  typedef particle_file_sequence::const_iterator particle_file_const_iterator;
  typedef ::xsd::cxx::tree::traits< particle_file_type, char > particle_file_traits;

  const particle_file_sequence&
  particle_file () const;

  particle_file_sequence&
  particle_file ();

  void
  particle_file (const particle_file_sequence& s);

  // cuboid
  // 
  typedef ::cuboid_t cuboid_type;
  typedef ::xsd::cxx::tree::sequence< cuboid_type > cuboid_sequence;
  typedef cuboid_sequence::iterator cuboid_iterator;
  typedef cuboid_sequence::const_iterator cuboid_const_iterator;
  typedef ::xsd::cxx::tree::traits< cuboid_type, char > cuboid_traits;

  const cuboid_sequence&
  cuboid () const;

  cuboid_sequence&
  cuboid ();

  void
  cuboid (const cuboid_sequence& s);

  // sphere
  // 
  typedef ::sphere_t sphere_type;
  typedef ::xsd::cxx::tree::sequence< sphere_type > sphere_sequence;
  typedef sphere_sequence::iterator sphere_iterator;
  typedef sphere_sequence::const_iterator sphere_const_iterator;
  typedef ::xsd::cxx::tree::traits< sphere_type, char > sphere_traits;

  const sphere_sequence&
  sphere () const;

  sphere_sequence&
  sphere ();

  void
  sphere (const sphere_sequence& s);

  // membrane
  // 
  typedef ::membrane_t membrane_type;
  typedef ::xsd::cxx::tree::sequence< membrane_type > membrane_sequence;
  typedef membrane_sequence::iterator membrane_iterator;
  typedef membrane_sequence::const_iterator membrane_const_iterator;
  typedef ::xsd::cxx::tree::traits< membrane_type, char > membrane_traits;

  const membrane_sequence&
  membrane () const;

  membrane_sequence&
  membrane ();

  void
  membrane (const membrane_sequence& s);

  // Constructors.
  //
  simulation_input_t ();

  simulation_input_t (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

  simulation_input_t (const simulation_input_t& x,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

  virtual simulation_input_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~simulation_input_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  particle_file_sequence particle_file_;
  cuboid_sequence cuboid_;
  sphere_sequence sphere_;
  membrane_sequence membrane_;
};

class iteration_output_t: public ::xml_schema::type
{
  public:
  // base_filename
  // 
  typedef ::xml_schema::string base_filename_type;
  typedef ::xsd::cxx::tree::traits< base_filename_type, char > base_filename_traits;

  const base_filename_type&
  base_filename () const;

  base_filename_type&
  base_filename ();

  void
  base_filename (const base_filename_type& x);

  void
  base_filename (::std::auto_ptr< base_filename_type > p);

  // output_freq
  // 
  typedef ::xml_schema::unsigned_int output_freq_type;
  typedef ::xsd::cxx::tree::traits< output_freq_type, char > output_freq_traits;

  const output_freq_type&
  output_freq () const;

  output_freq_type&
  output_freq ();

  void
  output_freq (const output_freq_type& x);

  // Constructors.
  //
  iteration_output_t (const base_filename_type&,
                      const output_freq_type&);

  iteration_output_t (const ::xercesc::DOMElement& e,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

  iteration_output_t (const iteration_output_t& x,
                      ::xml_schema::flags f = 0,
                      ::xml_schema::container* c = 0);

  virtual iteration_output_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~iteration_output_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< base_filename_type > base_filename_;
  ::xsd::cxx::tree::one< output_freq_type > output_freq_;
};

class result_output_t: public ::xml_schema::type
{
  public:
  // filename
  // 
  typedef ::xml_schema::string filename_type;
  typedef ::xsd::cxx::tree::traits< filename_type, char > filename_traits;

  const filename_type&
  filename () const;

  filename_type&
  filename ();

  void
  filename (const filename_type& x);

  void
  filename (::std::auto_ptr< filename_type > p);

  // Constructors.
  //
  result_output_t (const filename_type&);

  result_output_t (const ::xercesc::DOMElement& e,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

  result_output_t (const result_output_t& x,
                   ::xml_schema::flags f = 0,
                   ::xml_schema::container* c = 0);

  virtual result_output_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~result_output_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< filename_type > filename_;
};

class simulation_output_t: public ::xml_schema::type
{
  public:
  // iteration
  // 
  typedef ::iteration_output_t iteration_type;
  typedef ::xsd::cxx::tree::optional< iteration_type > iteration_optional;
  typedef ::xsd::cxx::tree::traits< iteration_type, char > iteration_traits;

  const iteration_optional&
  iteration () const;

  iteration_optional&
  iteration ();

  void
  iteration (const iteration_type& x);

  void
  iteration (const iteration_optional& x);

  void
  iteration (::std::auto_ptr< iteration_type > p);

  // result
  // 
  typedef ::result_output_t result_type;
  typedef ::xsd::cxx::tree::optional< result_type > result_optional;
  typedef ::xsd::cxx::tree::traits< result_type, char > result_traits;

  const result_optional&
  result () const;

  result_optional&
  result ();

  void
  result (const result_type& x);

  void
  result (const result_optional& x);

  void
  result (::std::auto_ptr< result_type > p);

  // Constructors.
  //
  simulation_output_t ();

  simulation_output_t (const ::xercesc::DOMElement& e,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

  simulation_output_t (const simulation_output_t& x,
                       ::xml_schema::flags f = 0,
                       ::xml_schema::container* c = 0);

  virtual simulation_output_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~simulation_output_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  iteration_optional iteration_;
  result_optional result_;
};

class simulation_t: public ::xml_schema::type
{
  public:
  // parameter
  // 
  typedef ::simulation_parameters_t parameter_type;
  typedef ::xsd::cxx::tree::traits< parameter_type, char > parameter_traits;

  const parameter_type&
  parameter () const;

  parameter_type&
  parameter ();

  void
  parameter (const parameter_type& x);

  void
  parameter (::std::auto_ptr< parameter_type > p);

  // force-calculator
  // 
  typedef ::simulation_force_calculator_t force_calculator_type;
  typedef ::xsd::cxx::tree::traits< force_calculator_type, char > force_calculator_traits;

  const force_calculator_type&
  force_calculator () const;

  force_calculator_type&
  force_calculator ();

  void
  force_calculator (const force_calculator_type& x);

  void
  force_calculator (::std::auto_ptr< force_calculator_type > p);

  // input
  // 
  typedef ::simulation_input_t input_type;
  typedef ::xsd::cxx::tree::traits< input_type, char > input_traits;

  const input_type&
  input () const;

  input_type&
  input ();

  void
  input (const input_type& x);

  void
  input (::std::auto_ptr< input_type > p);

  // output
  // 
  typedef ::simulation_output_t output_type;
  typedef ::xsd::cxx::tree::traits< output_type, char > output_traits;

  const output_type&
  output () const;

  output_type&
  output ();

  void
  output (const output_type& x);

  void
  output (::std::auto_ptr< output_type > p);

  // Constructors.
  //
  simulation_t (const parameter_type&,
                const force_calculator_type&,
                const input_type&,
                const output_type&);

  simulation_t (::std::auto_ptr< parameter_type >&,
                ::std::auto_ptr< force_calculator_type >&,
                ::std::auto_ptr< input_type >&,
                ::std::auto_ptr< output_type >&);

  simulation_t (const ::xercesc::DOMElement& e,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

  simulation_t (const simulation_t& x,
                ::xml_schema::flags f = 0,
                ::xml_schema::container* c = 0);

  virtual simulation_t*
  _clone (::xml_schema::flags f = 0,
          ::xml_schema::container* c = 0) const;

  virtual 
  ~simulation_t ();

  // Implementation.
  //
  protected:
  void
  parse (::xsd::cxx::xml::dom::parser< char >&,
         ::xml_schema::flags);

  protected:
  ::xsd::cxx::tree::one< parameter_type > parameter_;
  ::xsd::cxx::tree::one< force_calculator_type > force_calculator_;
  ::xsd::cxx::tree::one< input_type > input_;
  ::xsd::cxx::tree::one< output_type > output_;
};

#include <iosfwd>

#include <xercesc/sax/InputSource.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMErrorHandler.hpp>

// Parse a URI or a local file.
//

::std::auto_ptr< ::simulation_t >
simulation (const ::std::string& uri,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (const ::std::string& uri,
            ::xml_schema::error_handler& eh,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (const ::std::string& uri,
            ::xercesc::DOMErrorHandler& eh,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

// Parse std::istream.
//

::std::auto_ptr< ::simulation_t >
simulation (::std::istream& is,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (::std::istream& is,
            ::xml_schema::error_handler& eh,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (::std::istream& is,
            ::xercesc::DOMErrorHandler& eh,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (::std::istream& is,
            const ::std::string& id,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (::std::istream& is,
            const ::std::string& id,
            ::xml_schema::error_handler& eh,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (::std::istream& is,
            const ::std::string& id,
            ::xercesc::DOMErrorHandler& eh,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

// Parse xercesc::InputSource.
//

::std::auto_ptr< ::simulation_t >
simulation (::xercesc::InputSource& is,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (::xercesc::InputSource& is,
            ::xml_schema::error_handler& eh,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (::xercesc::InputSource& is,
            ::xercesc::DOMErrorHandler& eh,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

// Parse xercesc::DOMDocument.
//

::std::auto_ptr< ::simulation_t >
simulation (const ::xercesc::DOMDocument& d,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

::std::auto_ptr< ::simulation_t >
simulation (::xml_schema::dom::auto_ptr< ::xercesc::DOMDocument >& d,
            ::xml_schema::flags f = 0,
            const ::xml_schema::properties& p = ::xml_schema::properties ());

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

#endif // SRC_XMLINPUT_SIMULATION_H
